name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [${{ github.event.inputs.docker_images }}]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Image
      run: |
        docker pull "${{ matrix.image }}" --platform "linux/amd64"
        docker save "${{ matrix.image }}" -o "${{ matrix.image //\//_ }}-amd64.tar"

    - name: Compress the TAR files
      if: matrix.image == 'alpine:latest'
      run: tar -czf x86-64-images.tar.gz *-amd64.tar

    - name: Upload artifact
      if: matrix.image == 'alpine:latest'
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: x86-64-images.tar.gz
        retention-days: 60

    - name: Clean up intermediate files
      if: matrix.image == 'alpine:latest'
      run: |
        rm *-amd64.tar

